backend:
  name: git-gateway
  branch: master

# local_backend: true
# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "img"

collections:
  - name: "exercicios"
    label: "Exercicios"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Sumario"
        name: "summary"
        widget: "text"
        required: false

      - label: "Categorías nas que aparece"
        name: "tags"
        widget: "relation" 
        collection: "etiquetas"
        value_field: "id"
        display_fields: ["title"]
        search_fields: ["title"]
        multiple: true

      - label: "Ocultar"
        name: "draft"
        widget: "boolean"
        default: false
        required: false

      - label: "Corpo"
        name: "body"
        widget: "markdown"
        required: false

  # Páxinas
  - name: "paxinas"
    label: "Páxinas"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Corpo"
        name: "body"
        widget: "markdown"
        required: false

  # Categorías
  - name: "etiquetas"
    label: "Categorías"
    folder: "categories"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Nome"
        name: "title"
        widget: "string"
      
      - label: "Identificador"
        name: "id"
        widget: "string"

      - label: "Categorías nas que aparece"
        name: "tags"
        widget: "relation" 
        collection: "etiquetas"
        value_field: "id"
        display_fields: ["title"]
        search_fields: ["title"]
        multiple: true

      - label: "Corpo"
        name: "body"
        widget: "markdown"
        required: false
